# Run tests

name: Integration Tests

on:
  pull_request: # Run on all pull requests
  push:
    branches:   # Run on any push to master
      - master
  schedule:     # Run weekly on master
    - cron: 0 2 * * 1
      branches: master


jobs:
  build-unittests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 #Checkout the project from git
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
