# Run tests

name: Integration Tests

on:
  pull_request: # Run on all pull requests
  push:
    branches:   # Run on any push to master
      - master
  schedule:     # Run weekly on master

    - cron: 0 2 * * 1
      branches: master


jobs:
  build-unittests:
    runs-on: ubuntu-20.04 #See pre-installed software at https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

    steps:
    - uses: actions/checkout@v2 #Checkout the project from git
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: DeLaGuardo/setup-clojure@master
      with:
        # To use Clojure CLI 1.10.1.561 based on tools.deps
        cli: '1.10.1.469'
        lein: latest
    - run: lein test
